#include "tmp/assemble.cpp"
#include "tmp/assemble1.cpp"
#include "tmp/suppliers.cpp"
#include "tmp/suppliers1.cpp"
#include "tmp/supply.cpp"
#include "tmp/supply1.cpp"
#include "tmp/supply2.cpp"
#include "tmp/partHash.cpp"
#include "tmp/partHash1.cpp"
#include "tmp/warehouses.cpp"
#include "tmp/warehouses1.cpp"
#include "tmp/products.cpp"
#include "tmp/products1.cpp"
#include "tmp/stored.cpp"
#include "tmp/stored1.cpp"
#include "tmp/stored2.cpp"
#include "tmp/prodName.cpp"

