type aggreg2.h > temp.h
type array.h >> temp.h
type binheap.h >> temp.h
type bitarray.h >> temp.h
type doublink.h >> temp.h
type general.h >> temp.h
type hash.h >> temp.h
type llist1.h >> temp.h
type llist2.h >> temp.h
type name.h >> temp.h
type ring1.h >> temp.h
type ring2.h >> temp.h
type singlink.h >> temp.h
type stack.h >> temp.h
type stlVector1.h >> temp.h
type stlVector2.h >> temp.h
